Detailed colored coin functional test
chaintope/tapyrus-core pull request #142
Opened 2021-06-28 04:45 UTC by Naviabheeman

improved functional test to include all address types and coloured coin types

2021-08-10 08:02 UTC, azuchi requested changes

2021-08-10 08:02 UTC, azuchi commented on test/functional/wallet_coloredcoin.py
> +        createrawtransaction
```suggestion
        7. createrawtransaction
```

2021-08-10 08:02 UTC, azuchi commented on test/functional/wallet_coloredcoin.py
> +        sendtoaddress
```suggestion
        8. sendtoaddress
```

2021-08-11 05:56 UTC, Naviabheeman commented on src/wallet/rpcwallet.cpp
> +#include <wallet/fees.h>
No, its not needed. I'll remove it.

2021-09-03 02:23 UTC, merged