RPC update part -2 : Removing account api
chaintope/tapyrus-core pull request #152
Opened 2021-08-08 07:35 UTC by Naviabheeman

This PR is after #150. 
all 'account' and 'dummy' parameters are removed from the RPC layer
Test cases are updated

2021-08-20 00:52 UTC, azuchi commented
@Naviabheeman can you rebase this?

2021-08-24 04:13 UTC, azuchi requested changes
`prioritisetransaction` still has `dummy`.

2021-08-24 04:18 UTC, azuchi commented on src/wallet/rpcwallet.cpp
>  static CTransactionRef SendMoney(CWallet * const pwallet, const CTxDestination &address, CAmount nValue, bool fSubtractFeeFromAmount, const CCoinControl& coin_control, mapValue_t mapValue, std::strin
The argument `fromAccount` is still here.

2021-08-30 17:26 UTC, Naviabheeman commented
> `prioritisetransaction` still has `dummy`.

@azuchi, can we remove this RPC? it seems to be deprecated.

2021-08-31 06:27 UTC, azuchi commented
> > `prioritisetransaction` still has `dummy`.
> 
> @azuchi, can we remove this RPC? it seems to be deprecated.

@Naviabheeman OK.

2021-09-01 06:03 UTC, azuchi approved these changes

2021-09-01 06:03 UTC, merged