UTXO cache trace points and sample scripts
chaintope/tapyrus-core pull request #215
Opened 2022-07-20 17:57 UTC by Naviabheeman

This PR ports utxo cache trace points from bitcoin core to Tapyrus-core. It includes the python functional tests for the tracepoints using bcc(python-bpfcc). However these scripts do not run successfully in the ubuntu 18 used in CI or in the docker environment. SO these are disabled now. the bpftrce scripts(.bt) work fine.

2023-08-31 08:57 UTC, azuchi requested changes

2023-08-31 08:57 UTC, azuchi commented on test/functional/interface_usdt_utxocache.py
> +            See https://github.com/bitcoin/bitcoin/blob/master/doc/tracing.md#tracepoint-utxocacheflush"""
This needs to be replaced with a valid link on the Tapyrus Core repository.

2023-08-31 08:57 UTC, azuchi commented on doc/build-unix.md
> +=======
Looks like a merge mistake.

2023-08-31 08:57 UTC, azuchi commented on doc/build-unix.md
> +>>>>>>> 82a6d0d55a (add tracepoints to utco cache)
Looks like a merge mistake

2023-08-31 08:57 UTC, azuchi commented on contrib/tracing/README.md
> +### log_utxocache_flush.py
This file not found.

2023-08-31 08:57 UTC, azuchi commented on contrib/tracing/README.md
> +### log_utxos.bt
This file not found.

2023-09-01 06:55 UTC, Naviabheeman commented on contrib/tracing/README.md
> +### log_utxocache_flush.py
fixed!

2023-09-01 06:55 UTC, Naviabheeman commented on contrib/tracing/README.md
> +### log_utxos.bt
fixed!

2023-10-20 04:59 UTC, azuchi approved these changes

2023-10-20 04:59 UTC, merged