Refactor files
chaintope/tapyrus-core pull request #298
Opened 2024-03-01 13:09 UTC by Naviabheeman

This PR is only refactoring of validation.cpp file. There is no code modification, it is only code move. This PR does not change behaviour. No new tests are added. 

New files:
chainstate.h and chainstate.cpp
 - these two files now contain all the chain state class and global chain state, g_chainstate.
 cs_main.h and cs_main.cpp
- This is similar to bitcoin. These files contains global mutex cs_main and cs_LastBlockFile. The critical sections are accessible from multiple files now.
file_io.h and file_io.cpp
- All disk operations are moved to these new files
scriptcheck.h
- contains CScriptCheck class
verifydb.h and verifydb.cpp
- contains CVerifyDB class
blockprune.h and blockprune.cpp
- global functions that are related to block pruning are in these files

2024-07-22 05:55 UTC, azuchi requested changes

2025-02-27 02:15 UTC, azuchi requested changes
Please fix following warnings:

```
blockprune.cpp:108:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint32_t’ {aka ‘unsigned int’} [-Wsign-compare]
  108 |     if (chainActive.Tip()->nHeight <= nPruneAfterHeight) {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
...

chainstate.cpp:611:22: warning: unused variable ‘flags’ [-Wunused-variable]
  611 |         unsigned int flags = GetBlockScriptFlags(pindex);
      |                      ^~~~~
...

file_io.cpp:371:18: warning: unused variable ‘coins_count’ [-Wunused-variable]
  371 |     const size_t coins_count = pcoinsTip->GetCacheSize();
      |                  ^~~~~~~~~~~
file_io.cpp:372:18: warning: unused variable ‘coins_mem_usage’ [-Wunused-variable]
  372 |     const size_t coins_mem_usage = pcoinsTip->DynamicMemoryUsage();
      |                  ^~~~~~~~~~~~~~~
...

 2365 |         CValidationState& state = opt.state;
      |                           ^~~~~
...

```

2025-02-27 02:19 UTC, azuchi commented on cmake/modules/FindUPNP.cmake
> +find_brew_prefix(BREW_HINT_UPNP miniupnpc)
Write homebrew-related code in a code block that has been confirmed to be for macOS like bellow:

https://github.com/bitcoin/bitcoin/blob/master/cmake/module/FindBerkeleyDB.cmake#L31-L33

Please modify FindBerkeleyDB.cmake in the same way.

2025-02-27 02:24 UTC, azuchi commented on test/functional/test_framework/script.py
> +MAX_SCRIPT_SIZE = 10000
This change unnecessary, because duplicate L19.

2025-02-27 02:29 UTC, azuchi commented on src/consensus/validation.h
> +    std::string Describe() const {
This method is not used?

2025-02-27 02:38 UTC, azuchi commented on src/leveldb/db/db_impl.cc
> +#include <deque>
Why this include need?

2025-02-27 02:40 UTC, azuchi commented on src/policy/packages.cpp
> +   if(!CheckPackage(package, state))
This change not necessary.

2025-02-27 05:12 UTC, azuchi commented on src/cs_main.h
> +extern RecursiveMutex cs_LastBlockFile;
In Bitcoin, it seems there is only cs_main, but what is cs_LastBlockFile for?

2025-02-27 05:14 UTC, azuchi commented on src/file_io.cpp
> +bool LoadMempool(void)
```suggestion
bool LoadMempool()
```

2025-03-03 07:42 UTC, Naviabheeman commented on src/cs_main.h
> +extern RecursiveMutex cs_LastBlockFile;
This is another global mutex which is shared between multiple files. So it is needed in a common place. In bitcoin, this is moved inside a new class called block manager.

2025-03-05 03:00 UTC, azuchi commented on cmake/modules/FindBerkeleyDB.cmake
>  include(BrewHelper)
Shouldn't this include also be executed only when CMAKE_HOST_APPLE is specified?

2025-03-12 00:50 UTC, azuchi approved these changes

2025-03-12 00:50 UTC, merged