Security fix6 getblocktxn
chaintope/tapyrus-core pull request #318
Opened 2024-11-03 11:03 UTC by Naviabheeman

Port security fix for "Disclosure of hindered block propagation due to mutated blocks
https://bitcoincore.org/en/2024/10/08/disclose-mutated-blocks-hindering-propagation/" from OR #27608  from bitcoin to fix hindered block propagation due to mutated blocks
The changes are in 'MarkBlockAsReceived' which is renamed to  'RemoveBlockRequest' in bitcoin.  processing of compact block message is updated to count the number of peers from which the missing block transactions are sought.

2024-11-15 02:43 UTC, azuchi requested changes

2024-11-15 02:43 UTC, azuchi commented on src/net_processing.cpp
> +     return true;
This change is not necessary.

2024-11-15 02:44 UTC, azuchi commented
Is there any testing for the fix in #26898?

2024-11-15 05:57 UTC, Naviabheeman commented
> Is there any testing for the fix in #26898?

The changes in  _#26898_ were made to fix the crash I mentioned. Before this change, when the same block was received from multiple peers, '_tapyrusd_' would exit at the assertions as the header was a `nullptr`. The null pointer is fixed by _#27626_. It makes sure that the header is always initialised. 
So I think the tests in `p2p_compactblocks.py`should be enough. Old tests verify compact block reconstruction with missing transactions. The new scenario verifies the full flow by receiving compactblocks (for a new block) from more than 3 peers . Block reconstruction from compact block and node accepting the compact block/txn only from the peer which was requested are both verified.

2024-11-18 06:27 UTC, azuchi approved these changes

2024-11-18 08:10 UTC, merged