v0.6.0 release notes
chaintope/tapyrus-core pull request #322
Opened 2024-11-27 12:48 UTC by Naviabheeman

All bitcoin release notes are removed.
Tapyrus release notes are moved to **doc/release-notes** from **doc/release-notes/tapyrus**
Man pages of new binaries are updated

2024-12-16 04:55 UTC, azuchi requested changes
Some generated files still contain 0.5.2 references.

* libtapyrusconsensus..pm
* doc/Doxyfile
* doc/man/Makefile
* share/setup.nsi
* share/qt/info.plist
* src/Makefile
* src/config/bitcoin-config.h

Try grep to see if there are any more.

2024-12-16 10:34 UTC, Naviabheeman commented
> Some generated files still contain 0.5.2 references.
> 
> Try grep to see if there are any more.

Sorry, I had not checked in `configure` script. That is why these files were generated with the old version number

2024-12-17 05:13 UTC, azuchi commented on doc/man/tapyrus-cli.1
> +Tapyrus Core RPC client version v0.6.0.0\-2e3b2207e\-dirty
Can you remove `\-2e3b2207e\-dirty` part along with other man pages.

2024-12-17 05:34 UTC, azuchi requested changes

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +It is recommended to upgrade all older nodes to the latest release as it contains fixes to vulnerabilities. If you are running a node on tapyrus testnet follow the instruction in [getting_started](do
```suggestion
It is recommended to upgrade all older nodes to the latest release as it contains fixes to vulnerabilities. If you are running a node on tapyrus testnet follow the instruction in [getting_started](doc/tapyrus/getting_started.md#how-to-start-a-node-on-tapyrus-testnet) to start a new Tapyrus v0.6.0 node.
```

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +If you are running a private tapyrus network using versions v0.3.0, v0.4.0 or v0.4.1, v0.5.0, v0.5.1, v0.5.2 shut it down. Wait until it has completely shut down. Follow the instruction in [getting_s
```suggestion
If you are running a private tapyrus network using versions v0.3.0, v0.4.0 or v0.4.1, v0.5.0, v0.5.1, v0.5.2 shut it down. Wait until it has completely shut down. Follow the instruction in [getting_started](doc/tapyrus/getting_started.md#how-to-start-a-new-tapyrus-network) to start a new Tapyrus v0.6.0 network. 
```

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +If you are running a private tapyrus network using versions v0.3.0, v0.4.0 or v0.4.1, v0.5.0, v0.5.1, v0.5.2 shut it down. Wait until it has completely shut down. Follow the instruction in [getting_s
Also, I think it would be better to refer to it as "older versions" rather than listing all versions.

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +Tapyrus blockchain created by older versions(v0.3.0, v0.4.0 and v0.4.1) is not compatible with v0.6.0 and vice-versa.
Please explain how it is incompatible.

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +This release allows the size of each block in a Tapyrus network to be increased from the default 1MB. This is done with the help of a new xfield type. When the block size is changed using the xfield
Could you please add a link to a page that explains the new xfield type (`doc/tapyrus/signedblocks.md`)and outline the steps to take when changing the block size?

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +- Fix vulnerabilities inherited from bitcoin core.
Please list and provide a brief description of each vulnerability you fixed.

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +- use newer version of all dependencies.
```suggestion
- Use newer version of all dependencies.
```

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +- remove usage of system and thread boost libraries and use std c++17 libraries.
```suggestion
- Remove usage of system and thread boost libraries and use std c++17 libraries.
```

2024-12-17 05:34 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
Please include a PR link for each changes listed below, and please add any PRs not listed here if exist.

2024-12-20 05:13 UTC, azuchi requested changes

2024-12-20 05:13 UTC, azuchi commented on doc/release-notes/release-notes-0.6.0.md
> +  *Fix vulnerabilities inherited from bitcoin core:*
```suggestion
*Fix vulnerabilities inherited from bitcoin core:*
```

2024-12-23 00:01 UTC, azuchi approved these changes

2024-12-23 00:01 UTC, merged